Content/python movie demo
neo4j-documentation/developer-guides pull request #26
Opened 2020-09-16 18:43 UTC by whatSocks

2020-09-16 18:44 UTC, whatSocks commented
[] rebase + squash
[] get review
[] update section about deployment

2020-09-16 21:55 UTC, ElaineRosenberg commented
Suggestions:
1. Call it a tutorial, not a course.
2. In Intro code blocks (before they do the setup), make them[source, cypher, role=nocopy,noplay] since they have not yet created the sandbox or will have access to the data.

I will need to spend more time on this to give you useful feedback, but it is looking great!

2020-09-17 13:29 UTC, ElaineRosenberg requested changes
Suggestions:

1. Call it a tutorial, not a course.
2. In Intro code blocks (before they do the setup), make them[source, cypher, role=nocopy,noplay] since they have not yet created the sandbox or will have access to the data.
3. Lines 100-101 do not match the query result. I would change the query to use movie again:
    MATCH (p:Person)-[:ACTED_IN]->(m:Movie)
RETURN p, collect(m.title)
4. For learning more about Cypher, also point to the Introduction to Neo4j 4.0 course (https://neo4j.com/graphacademy/online-training/introduction-to-neo4j-40/)
5. Line 156: inthe. 
6. Use Front-end in heading, front-end everywhere else. Don't use frontend
7. I suggest that you clearly mark the steps to get the application running with headers:
   Step 1: **Clone the repository** with a link to it    
   Step 2: **Start the database**. (which includes all steps to create the sandbox)
   Step 3: **Edit the connection information for the database** (include steps to grab the credentials from the sandbox and place them in the app.py file)
    Step 4: **Start the Flask API** (including steps to verify)
    Step 5: **Start the ReactJS Front-end**  (including steps for testing the app initially)
7. In the subsequent walkthrough specify [source, python, role=nocopy]  You are just showing them the code and they should not have to copy it.
8. Line 297, I would remove [source,shell] It is simply text that you want to show
9. Replace lines 327-329 with:
[square]
* `password`: The hashed version of the user’s chosen password
* `api_key`: The user’s API key, which the user uses to authenticate requests
* `username`: The user’s chosen username
10. Remove [source,shell] from line 353 & 374 - you just want to display the response as text
11. use [source,python role=nocopy] for line 384
12. Take [source,shell] out at line 476, 492, 508, 543
13. "Below is a rather empty user profile for a freshly created user:" Is this referring to what you will show next? Perhaps it should be worded:  "Next, you will..." (line 525)
14. Is the user supposed to add the RateMovie code or is it already there? If it is already there then you should make it nocopy (line 549)
15. Line 584, make it bold and make the response a text block (remove [source,shell] from line 593)
16. Is MovieListRatedByMe existing code? It should be nocopy  on line 611
17. Is this existing code? if so, make it nocopy (lines 666, 692

2020-09-24 16:59 UTC, ElaineRosenberg approved these changes

2020-09-24 16:59 UTC, merged